### ISSUE TITLE
Can we export Retail Store Detection last_yolov5s_results.pt weights to tflite to run inference on mobile devices ?

### ISSUE THREAD

**Issue by SanjayGhanagiri** [shayanalibhatti/Retail-Store-Item-Detection-using-YOLOv5#7]
Am trying to convert the last_yolov5s_results.pt to tflite using the official Yolov5 suggested method to convert .pt weights to tflite 
https://github.com/ultralytics/yolov5/blob/master/export.py

But I get the below error in fusing layers step 
Please let me know if there is an alternative way to convert last_yolov5s_results.pt  to tflite.

`
Fusing layers... 
Model summary: 199 layers, 6853110 parameters, 0 gradients
Traceback (most recent call last):
  File "/content/yolov5/export.py", line 653, in <module>
    main(opt)
  File "/content/yolov5/export.py", line 648, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov5/export.py", line 549, in run
    y = model(im)  # dry runs
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov5/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/content/yolov5/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov5/models/yolo.py", line 59, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'm'`

**Comment by shayan-NECX** [comment]
Google 'Detect' object has no attribute 'm'  . It is a known issue probably because of latest version of Yolov5. https://github.com/ultralytics/yolov5/issues/690
